'use client'

import { useState, useEffect, useRef } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { CoverLetterResponse, CoverLetterTone, CoverLetterLength } from '@/types'
import { Loader2, Copy, Check, Download, RefreshCw, Save } from 'lucide-react'
import { downloadCoverLetterAsDocx } from '@/lib/cover-letter-export'

interface CoverLetterPanelProps {
  resumeText: string
  jobDescription: string
  companyName?: string
  roleTitle?: string
  userName?: string
  contactInfo?: string
  autoGenerate?: boolean
}

export function CoverLetterPanel({
  resumeText,
  jobDescription,
  companyName,
  roleTitle,
  userName,
  contactInfo,
  autoGenerate = false,
}: CoverLetterPanelProps) {
  const [coverLetter, setCoverLetter] = useState<string>('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [tone, setTone] = useState<CoverLetterTone>('Professional')
  const [length, setLength] = useState<CoverLetterLength>('Standard')
  const [copied, setCopied] = useState(false)
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)
  const hasAutoGenerated = useRef(false)

  const generateCoverLetter = async (regenerate = false) => {
    if (!resumeText.trim() || !jobDescription.trim()) {
      setError('Resume text and job description are required')
      return
    }

    setLoading(true)
    setError(null)
    setSaved(false)

    try {
      const response = await fetch('/api/cover-letter', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          resumeText: resumeText.trim(),
          jobDescription: jobDescription.trim(),
          tone,
          length,
          companyName,
          roleTitle,
          userName,
          contactInfo,
        }),
      })

      if (!response.ok) {
        const errorData = await response.json()
        throw new Error(errorData.error || 'Failed to generate cover letter')
      }

      const data: CoverLetterResponse = await response.json()
      setCoverLetter(data.coverLetter)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred')
    } finally {
      setLoading(false)
    }
  }

  // Auto-generate cover letter when component mounts with autoGenerate prop
  useEffect(() => {
    if (autoGenerate && !hasAutoGenerated.current && resumeText.trim() && jobDescription.trim()) {
      hasAutoGenerated.current = true
      generateCoverLetter(false)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [autoGenerate, resumeText, jobDescription])

  const handleCopy = async () => {
    if (!coverLetter) return
    await navigator.clipboard.writeText(coverLetter)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    if (!coverLetter) return
    downloadCoverLetterAsDocx(coverLetter, {
      userName: userName || 'Your Name',
      contactInfo: contactInfo || '',
      companyName: companyName || '',
      roleTitle: roleTitle || '',
    })
  }

  const handleSave = async () => {
    if (!coverLetter.trim()) {
      setError('No cover letter to save')
      return
    }

    setSaving(true)
    setError(null)

    try {
      const title = `Cover Letter${roleTitle ? ` - ${roleTitle}` : ''}${companyName ? ` - ${companyName}` : ''}`
      
      const response = await fetch('/api/cover-letter/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title,
          content: coverLetter,
          tone,
          length,
          companyName,
          roleTitle,
        }),
      })

      if (!response.ok) {
        const errorData = await response.json()
        throw new Error(errorData.error || 'Failed to save cover letter')
      }

      setSaved(true)
      setTimeout(() => setSaved(false), 3000)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to save cover letter')
    } finally {
      setSaving(false)
    }
  }

  return (
    <Card className="mt-6">
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle>Cover Letter</CardTitle>
          <div className="flex gap-2">
            {!coverLetter && (
              <Button
                onClick={() => generateCoverLetter(false)}
                disabled={loading || !resumeText.trim() || !jobDescription.trim()}
                size="sm"
              >
                {loading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating...
                  </>
                ) : (
                  'Generate Cover Letter'
                )}
              </Button>
            )}
            {coverLetter && (
              <Button
                onClick={() => generateCoverLetter(true)}
                disabled={loading}
                variant="outline"
                size="sm"
              >
                {loading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Regenerating...
                  </>
                ) : (
                  <>
                    <RefreshCw className="mr-2 h-4 w-4" />
                    Regenerate
                  </>
                )}
              </Button>
            )}
          </div>
        </div>
      </CardHeader>
      <CardContent>
        {!coverLetter && !loading && (
          <div className="space-y-4 mb-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label htmlFor="tone">Tone</Label>
                <Select value={tone} onValueChange={(value) => setTone(value as CoverLetterTone)}>
                  <SelectTrigger id="tone">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Professional">Professional</SelectItem>
                    <SelectItem value="Enthusiastic">Enthusiastic</SelectItem>
                    <SelectItem value="Concise">Concise</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label htmlFor="length">Length</Label>
                <Select value={length} onValueChange={(value) => setLength(value as CoverLetterLength)}>
                  <SelectTrigger id="length">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Short">Short (~200-250 words)</SelectItem>
                    <SelectItem value="Standard">Standard (~300-400 words)</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          </div>
        )}

        {error && (
          <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded mb-4">
            {error}
          </div>
        )}

        {coverLetter && (
          <div className="space-y-4">
            <div>
              <Label htmlFor="cover-letter-content">Cover Letter Content</Label>
              <Textarea
                id="cover-letter-content"
                value={coverLetter}
                onChange={(e) => setCoverLetter(e.target.value)}
                className="min-h-[400px] mt-2 font-mono text-sm"
                placeholder="Cover letter will appear here..."
              />
            </div>

            <div className="flex flex-wrap gap-2">
              <Button onClick={handleCopy} variant="outline" size="sm">
                {copied ? (
                  <>
                    <Check className="mr-2 h-4 w-4" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="mr-2 h-4 w-4" />
                    Copy
                  </>
                )}
              </Button>
              <Button onClick={handleDownload} variant="outline" size="sm">
                <Download className="mr-2 h-4 w-4" />
                Download .docx
              </Button>
              <Button onClick={handleSave} variant="outline" size="sm" disabled={saving}>
                {saving ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Saving...
                  </>
                ) : saved ? (
                  <>
                    <Check className="mr-2 h-4 w-4" />
                    Saved!
                  </>
                ) : (
                  <>
                    <Save className="mr-2 h-4 w-4" />
                    Save Cover Letter
                  </>
                )}
              </Button>
            </div>
          </div>
        )}

        {loading && !coverLetter && (
          <div className="flex items-center justify-center py-12">
            <Loader2 className="h-8 w-8 animate-spin text-gray-400" />
            <span className="ml-3 text-gray-600">Generating your cover letter...</span>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

